"use strict";
/**
 * WhatsApp Endpoint Matrix — ProYonetim Merge Sonrası
 *
 * Tüm WhatsApp endpoint'lerinin auth, tenant, relay bağımlılığı
 * ve merge durumunu gösteren referans dokümanı.
 *
 * SOURCE OF TRUTH: Canlı Radore davranışı korunur.
 * Readdy bomb-proof startup + yeni modüler compat/delivery/audit katmanları.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RELAY_DEPENDENCIES = exports.ENDPOINT_SUMMARY = exports.WHATSAPP_ENDPOINT_MATRIX = void 0;
exports.WHATSAPP_ENDPOINT_MATRIX = [
    // ═══════════════════════════════════════════════════
    //  1. PRIMARY /api/whatsapp/* ENDPOINT'LER (Readdy Mevcut)
    // ═══════════════════════════════════════════════════
    {
        method: 'POST', path: '/api/whatsapp/site/connect',
        controller: 'handleSiteConnect', service: 'multiTenantConnect',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Token’dan company_id çözülür. Rate limit + lock mekanizması var.',
    },
    {
        method: 'POST', path: '/api/whatsapp/site/status',
        controller: 'handleSiteStatus', service: 'multiTenantStatus',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'getActiveWhatsAppContext ile Evolution API canlı state kontrolü.',
    },
    {
        method: 'GET', path: '/api/whatsapp/site/qr',
        controller: 'handleSiteQr', service: 'multiTenantStatus',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'QR base64 mevcut mu kontrol eder.',
    },
    {
        method: 'POST', path: '/api/whatsapp/site/disconnect',
        controller: 'handleSiteDisconnect', service: 'multiTenantDisconnect',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'SADECE ilgili firmanın instance’ını disconnect eder.',
    },
    {
        method: 'POST', path: '/api/whatsapp/site/reconnect',
        controller: 'handleSiteReconnect', service: 'multiTenantConnect + multiTenantDisconnect',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'disconnect + connect akışı. Instance kontrolü yapar.',
    },
    {
        method: 'POST', path: '/api/whatsapp/site/send',
        controller: 'handleSiteSend', service: 'sendEvolutionTextMessage',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Tekli mesaj. Direkt Evolution API gönderim + arşivleme.',
    },
    {
        method: 'POST', path: '/api/whatsapp/site/bulk-send',
        controller: 'handleSiteBulkSend', service: 'sendEvolutionBulkMessages',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Toplu mesaj. 50+ alıcı queue, 50 altı direkt gönderim.',
    },
    {
        method: 'POST', path: '/api/whatsapp/site/direct-send',
        controller: 'handleSiteDirectSend', service: 'sendEvolutionTextMessage',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Direkt gönderim. resolveCompanyContext + Evolution API.',
    },
    {
        method: 'POST', path: '/api/whatsapp/company/connect',
        controller: 'handleConnect', service: 'multiTenantConnect',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Geriye dönük company endpoint. Artık multiTenantConnect’e yönlendiriyor.',
    },
    {
        method: 'GET', path: '/api/whatsapp/company/status',
        controller: 'handleStatus', service: 'multiTenantStatus',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Geriye dönük company endpoint.',
    },
    {
        method: 'GET', path: '/api/whatsapp/company/qr',
        controller: 'handleQr', service: 'multiTenantStatus',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Geriye dönük company endpoint.',
    },
    {
        method: 'POST', path: '/api/whatsapp/company/disconnect',
        controller: 'handleDisconnect', service: 'multiTenantDisconnect',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Geriye dönük company endpoint.',
    },
    {
        method: 'POST', path: '/api/whatsapp/company/reconnect',
        controller: 'handleReconnect', service: 'multiTenantConnect',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Geriye dönük company endpoint.',
    },
    {
        method: 'POST', path: '/api/whatsapp/send',
        controller: 'handleSend', service: 'sendEvolutionTextMessage',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Legacy send. company_id bazlı.',
    },
    {
        method: 'POST', path: '/api/whatsapp/bulk/send',
        controller: 'handleBulkSend', service: 'sendEvolutionBulkMessages',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Legacy bulk send.',
    },
    {
        method: 'POST', path: '/api/whatsapp/direct/send',
        controller: 'handleDirectSend', service: 'sendEvolutionTextMessage',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Legacy direct send.',
    },
    {
        method: 'GET', path: '/api/whatsapp/health',
        controller: 'handleHealth', service: 'getHealth',
        authRequired: false, tenantCheck: false, siteCheck: false, companyCheck: false,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Public health check. No auth.',
    },
    {
        method: 'GET', path: '/api/whatsapp/health/enterprise',
        controller: 'handleEnterpriseHealth', service: 'getEnterpriseHealth',
        authRequired: true, tenantCheck: false, siteCheck: false, companyCheck: false,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Enterprise health with queue stats.',
    },
    {
        method: 'GET', path: '/api/whatsapp/diagnostics',
        controller: 'handleDiagnostics', service: 'runFullDiagnostics',
        authRequired: false, tenantCheck: false, siteCheck: false, companyCheck: false,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: '14 kontrol noktalı diagnostics. Public.',
    },
    {
        method: 'POST', path: '/api/whatsapp/diagnostics/heal',
        controller: 'handleHeal', service: 'healDiagnosticItem',
        authRequired: true, tenantCheck: false, siteCheck: false, companyCheck: false,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Self-healing endpoint.',
    },
    {
        method: 'GET', path: '/api/whatsapp/site/diagnostics',
        controller: 'handleSiteDiagnostics', service: 'getMultiTenantDiagnostics',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Firma bazlı tam diagnostics.',
    },
    {
        method: 'GET', path: '/api/whatsapp/sessions',
        controller: 'handleSessionList', service: 'whatsAppManager.getAllClients',
        authRequired: true, tenantCheck: false, siteCheck: false, companyCheck: false,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Aktif session listesi.',
    },
    {
        method: 'GET', path: '/api/whatsapp/queue/stats',
        controller: 'handleQueueStats', service: 'messageQueue.getStats',
        authRequired: true, tenantCheck: false, siteCheck: true, companyCheck: false,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Queue istatistikleri. siteId query param.',
    },
    {
        method: 'GET', path: '/api/whatsapp/channels',
        controller: 'handleGetChannels', service: 'getCompanyChannels',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Hibrit kanal yönetimi. CONNECTED_DEVICE + OFFICIAL_CLOUD_API.',
    },
    {
        method: 'POST', path: '/api/whatsapp/channels/default',
        controller: 'handleSetDefaultChannel', service: 'setDefaultChannel',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Varsayılan kanal değiştirme.',
    },
    {
        method: 'GET', path: '/api/whatsapp/site/archive/verify',
        controller: 'handleArchiveVerify', service: 'verifyArchiveRecord',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Archive kaydı doğrulama. Canlı gönderim testi için.',
    },
    {
        method: 'POST', path: '/api/whatsapp/webhook/evolution',
        controller: 'handleEvolutionWebhook', service: 'Evolution API webhook handler',
        authRequired: false, tenantCheck: false, siteCheck: false, companyCheck: false,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy daha güncel)',
        relayDependency: null,
        notes: 'Public webhook. Evolution API key doğrulaması içinde.',
    },
    // ═══════════════════════════════════════════════════
    //  2. COMPATIBILITY BRIDGE /api/instance/* (Canlıdan Yeni Aktarıldı)
    // ═══════════════════════════════════════════════════
    {
        method: 'POST', path: '/api/instance/connect/:siteId',
        controller: 'compatRouter /connect/:siteId', service: 'multiTenantConnect',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: false,
        mergeStatus: 'YENİ EKLENDİ (Canlıdan aktarıldı)',
        relayDependency: 'credentials-relay',
        notes: 'Eski relay sunucuları ve eski frontend versiyonları bu endpoint’i kullanabilir.',
    },
    {
        method: 'GET', path: '/api/instance/status/:siteId',
        controller: 'compatRouter /status/:siteId', service: 'multiTenantStatus',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: false,
        mergeStatus: 'YENİ EKLENDİ (Canlıdan aktarıldı)',
        relayDependency: 'credentials-relay',
        notes: 'Eski status endpoint’i.',
    },
    {
        method: 'POST', path: '/api/instance/send-text/:siteId',
        controller: 'compatRouter /send-text/:siteId', service: 'sendEvolutionTextMessage',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: false,
        mergeStatus: 'YENİ EKLENDİ (Canlıdan aktarıldı)',
        relayDependency: 'send-relay',
        notes: 'Eski send endpoint’i. JSONL log’a da yazar.',
    },
    {
        method: 'POST', path: '/api/instance/disconnect/:siteId',
        controller: 'compatRouter /disconnect/:siteId', service: 'multiTenantDisconnect',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: false,
        mergeStatus: 'YENİ EKLENDİ (Canlıdan aktarıldı)',
        relayDependency: null,
        notes: 'Eski disconnect endpoint’i.',
    },
    {
        method: 'GET', path: '/api/instance/send-logs/:siteId',
        controller: 'compatRouter /send-logs/:siteId', service: 'readWhatsAppSendLogs',
        authRequired: true, tenantCheck: false, siteCheck: true, companyCheck: false,
        liveExists: true, readdyExists: false,
        mergeStatus: 'YENİ EKLENDİ (Canlıdan aktarıldı)',
        relayDependency: null,
        notes: 'JSONL log dosyası okuma.',
    },
    {
        method: 'POST', path: '/api/instance/webhook/evolution',
        controller: 'compatRouter /webhook/evolution', service: 'handleEvolutionWebhook',
        authRequired: false, tenantCheck: false, siteCheck: false, companyCheck: false,
        liveExists: true, readdyExists: false,
        mergeStatus: 'YENİ EKLENDİ (Canlıdan aktarıldı)',
        relayDependency: null,
        notes: 'Webhook compatibility bridge. Mevcut webhook handler’a yönlendirir.',
    },
    {
        method: 'GET', path: '/api/instance/delivery-report/:siteId',
        controller: 'compatRouter /delivery-report/:siteId', service: 'getDeliverySummary',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: false,
        mergeStatus: 'YENİ EKLENDİ (Canlıdan aktarıldı)',
        relayDependency: null,
        notes: 'Delivery report compatibility endpoint.',
    },
    // ═══════════════════════════════════════════════════
    //  3. DELIVERY ROUTES /api/instance/delivery/* (Canlıdan Yeni Aktarıldı)
    // ═══════════════════════════════════════════════════
    {
        method: 'GET', path: '/api/instance/delivery/:siteId',
        controller: 'deliveryRouter /:siteId', service: 'getDeliverySummary',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: false,
        mergeStatus: 'YENİ EKLENDİ (Canlıdan aktarıldı)',
        relayDependency: null,
        notes: 'Site bazlı delivery özeti. Son 24 saat (query: hours).',
    },
    {
        method: 'GET', path: '/api/instance/delivery/:siteId/messages',
        controller: 'deliveryRouter /:siteId/messages', service: 'whatsapp_message_archive query',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: false,
        mergeStatus: 'YENİ EKLENDİ (Canlıdan aktarıldı)',
        relayDependency: null,
        notes: 'Detaylı delivery kayıtları. Limit/offset/pagination.',
    },
    {
        method: 'GET', path: '/api/instance/delivery/:siteId/pending',
        controller: 'deliveryRouter /:siteId/pending', service: 'whatsapp_message_archive query',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: false,
        mergeStatus: 'YENİ EKLENDİ (Canlıdan aktarıldı)',
        relayDependency: null,
        notes: 'Teslim edilmemiş mesajlar. SENT ama DELIVERED değil.',
    },
    {
        method: 'POST', path: '/api/instance/delivery/:siteId/refresh',
        controller: 'deliveryRouter /:siteId/refresh', service: 'archive lookup',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: false,
        mergeStatus: 'YENİ EKLENDİ (Canlıdan aktarıldı)',
        relayDependency: null,
        notes: 'Belirli providerMessageId için archive kaydını yenile.',
    },
    // ═══════════════════════════════════════════════════
    //  4. AUDIT ROUTES /api/instance/audit/* (Canlıdan Yeni Aktarıldı)
    // ═══════════════════════════════════════════════════
    {
        method: 'GET', path: '/api/instance/audit/logs',
        controller: 'auditRouter /logs', service: 'readAuditLogs',
        authRequired: true, tenantCheck: false, siteCheck: false, companyCheck: false,
        liveExists: true, readdyExists: false,
        mergeStatus: 'YENİ EKLENDİ (Canlıdan aktarıldı)',
        relayDependency: null,
        notes: 'Global audit log kayıtları (JSONL).',
    },
    {
        method: 'GET', path: '/api/instance/audit/:siteId',
        controller: 'auditRouter /:siteId', service: 'notification_delivery_logs query',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: false,
        mergeStatus: 'YENİ EKLENDİ (Canlıdan aktarıldı)',
        relayDependency: null,
        notes: 'Site bazlı audit kayıtları. notification_delivery_logs tablosundan.',
    },
    {
        method: 'GET', path: '/api/instance/audit/:siteId/stats',
        controller: 'auditRouter /:siteId/stats', service: 'whatsapp_message_archive stats',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: false,
        mergeStatus: 'YENİ EKLENDİ (Canlıdan aktarıldı)',
        relayDependency: null,
        notes: 'Site bazlı delivery rate, read rate istatistikleri.',
    },
    {
        method: 'MIDDLEWARE', path: '/* (POST /send* /connect* /reconnect*)',
        controller: 'whatsappAuditSendCapture', service: 'appendAuditLog + writeDbAuditLog',
        authRequired: false, tenantCheck: false, siteCheck: false, companyCheck: false,
        liveExists: true, readdyExists: false,
        mergeStatus: 'YENİ EKLENDİ (Canlıdan aktarıldı)',
        relayDependency: null,
        notes: 'Tüm send/connect/reconnect POST isteklerini yakalar. JSONL + DB’ye yazar.',
    },
    // ═══════════════════════════════════════════════════
    //  5. GERİYE DÖNÜK /api/whatsapp/* (Eski endpoint'ler)
    // ═══════════════════════════════════════════════════
    {
        method: 'POST', path: '/api/whatsapp/start',
        controller: 'handleConnect', service: 'multiTenantConnect',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy mevcut)',
        relayDependency: null,
        notes: 'Eski /start endpoint. Geriye dönük uyumlu.',
    },
    {
        method: 'POST', path: '/api/whatsapp/status',
        controller: 'handleStatus', service: 'multiTenantStatus',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy mevcut)',
        relayDependency: null,
        notes: 'Eski /status endpoint. Geriye dönük uyumlu.',
    },
    {
        method: 'POST', path: '/api/whatsapp/qr',
        controller: 'handleQr', service: 'multiTenantStatus',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy mevcut)',
        relayDependency: null,
        notes: 'Eski /qr endpoint. Geriye dönük uyumlu.',
    },
    {
        method: 'POST', path: '/api/whatsapp/disconnect',
        controller: 'handleDisconnect', service: 'multiTenantDisconnect',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy mevcut)',
        relayDependency: null,
        notes: 'Eski /disconnect endpoint. Geriye dönük uyumlu.',
    },
    {
        method: 'POST', path: '/api/whatsapp/reconnect',
        controller: 'handleReconnect', service: 'multiTenantConnect',
        authRequired: true, tenantCheck: true, siteCheck: true, companyCheck: true,
        liveExists: true, readdyExists: true,
        mergeStatus: 'Korundu (Readdy mevcut)',
        relayDependency: null,
        notes: 'Eski /reconnect endpoint. Geriye dönük uyumlu.',
    },
];
// ═══════════════════════════════════════════════════
//  ÖZET
// ═══════════════════════════════════════════════════
exports.ENDPOINT_SUMMARY = {
    totalEndpoints: exports.WHATSAPP_ENDPOINT_MATRIX.length,
    primaryApiEndpoints: exports.WHATSAPP_ENDPOINT_MATRIX.filter(e => e.path.startsWith('/api/whatsapp/')).length,
    compatBridgeEndpoints: exports.WHATSAPP_ENDPOINT_MATRIX.filter(e => e.path.startsWith('/api/instance/') && !e.path.includes('/delivery') && !e.path.includes('/audit')).length,
    deliveryEndpoints: exports.WHATSAPP_ENDPOINT_MATRIX.filter(e => e.path.startsWith('/api/instance/delivery')).length,
    auditEndpoints: exports.WHATSAPP_ENDPOINT_MATRIX.filter(e => e.path.startsWith('/api/instance/audit')).length,
    middlewareEntries: exports.WHATSAPP_ENDPOINT_MATRIX.filter(e => e.method === 'MIDDLEWARE').length,
    authRequired: exports.WHATSAPP_ENDPOINT_MATRIX.filter(e => e.authRequired).length,
    publicEndpoints: exports.WHATSAPP_ENDPOINT_MATRIX.filter(e => !e.authRequired).length,
    liveOnly: exports.WHATSAPP_ENDPOINT_MATRIX.filter(e => e.liveExists && !e.readdyExists).length,
    readdyOnly: exports.WHATSAPP_ENDPOINT_MATRIX.filter(e => !e.liveExists && e.readdyExists).length,
    bothExist: exports.WHATSAPP_ENDPOINT_MATRIX.filter(e => e.liveExists && e.readdyExists).length,
    withRelayDependency: exports.WHATSAPP_ENDPOINT_MATRIX.filter(e => e.relayDependency !== null).length,
};
// ═══════════════════════════════════════════════════
//  RELAY BAĞIMLILIKLARI ÖZETİ
// ═══════════════════════════════════════════════════
exports.RELAY_DEPENDENCIES = [
    {
        name: 'whatsapp-credentials-relay',
        path: '/var/www/proyonetim/whatsapp-credentials-relay/',
        pythonFile: 'server.py',
        purpose: 'Evolution API instance credentials yönetimi',
        relatedEndpoints: ['/api/instance/connect/:siteId', '/api/instance/status/:siteId'],
        serverStatus: 'SERVER_PROTECTED — canlı Radore’de korunacak',
    },
    {
        name: 'whatsapp-send-relay',
        path: '/var/www/proyonetim/whatsapp-send-relay/',
        pythonFile: 'server.py',
        purpose: 'WhatsApp mesaj gönderim relay’i',
        relatedEndpoints: ['/api/instance/send-text/:siteId'],
        serverStatus: 'SERVER_PROTECTED — canlı Radore’de korunacak',
    },
    {
        name: 'person-resolve-relay',
        path: '/var/www/proyonetim/person-resolve-relay/',
        pythonFile: 'server.py',
        purpose: 'Resident → telefon numarası çözümleme',
        relatedEndpoints: ['/api/instance/send-text/:siteId (indirect)'],
        serverStatus: 'SERVER_PROTECTED — canlı Radore’de korunacak',
    },
];
//# sourceMappingURL=WHATSAPP_ENDPOINT_MATRIX.js.map